version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mtgdb
      - POSTGRES_USER=mtg_user
      - POSTGRES_PASSWORD=mtg_password
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://mtg_user:mtg_password@db/mtgdb
    depends_on:
      - db

volumes:
  pgdata:
